// Question pool. Format: ["question", "red answer", "yellow answer", "green answer", "blue answer"]
// To add a question, just add a new line. The quiz picks random ones every time.
const POOL = [
["At a family function, you usually...","Take charge of the arrangements","Chat with everyone and keep it lively","Help quietly wherever needed","Watch the schedule so nothing goes wrong"],
["Your phone battery is at 5%. You...","Find a charger now, no excuses","Text everyone one last message","Stay calm, it will be fine","Relax, you charged it earlier as always"],
["Your ideal job is...","Running my own team","Something with lots of people and new things","A calm place with good people","Research or an expert job"],
["It starts raining while you are out. You...","Run to find shelter fast","Dance in it and laugh","Share your umbrella with a friend","Check the weather app, you carried a raincoat"],
["In class, you are the one who...","Leads the group project","Makes everyone laugh","Helps classmates who are stuck","Gets top marks quietly"],
["You get a free day. Your first thought is...","What can I achieve today?","Who can I meet?","Rest and relax","Start that book or course I planned"],
["Your friends describe your room as...","Simple and made for work","Colourful and a bit messy","Cosy and comfortable","Neat and well organised"],
["When someone is late, you...","Get angry, time matters","Say it's okay, then talk about something fun","Wait patiently, no problem","Note it in your mind, a rule was broken"],
["Your favourite way to learn is...","Jump in and try","Learn with friends","Learn slowly, step by step","Study deeply on my own"],
["When you win something, you...","Want the next challenge","Celebrate loudly with everyone","Thank everyone who helped","Check how you can improve"],
["Choosing a restaurant, you...","Pick fast, no long talk","Pick the trendy, busy place","Pick where everyone agrees","Read reviews and the menu first"],
["A group project is falling behind. You...","Take over and fix it","Boost the team's mood","Quietly do extra work","Make a clear plan with tasks"],
["Your biggest strength is...","Courage","Charm","Loyalty","Intelligence"],
["You lose your keys. You...","Get frustrated and search fast","Laugh and ask everyone to help","Stay calm, they will show up","Retrace your steps one by one"],
["A teacher announces a surprise test. You...","Take it like a challenge","Joke about it with friends","Feel nervous but stay calm","Wish you had prepared more"],
["At a wedding, you are...","Organising things","On the dance floor","Helping the family","Watching and enjoying quietly"],
["Your friend is sad. You...","Tell them to be strong and fix it","Make them laugh","Sit with them and listen","Think about what caused it"],
["On social media, you...","Post your achievements","Post a lot and share everything","Look at friends' posts, rarely post","Read and research, post little"],
["For a big decision, you...","Trust your gut and go","Ask many friends","Think about how it affects others","Make a list of pros and cons"],
["People come to you for...","Direction","Fun","Comfort","Answers"],
["Your idea of a good team is...","A strong leader and a clear goal","Many friends and good energy","Trust and harmony","Clear roles and quality work"],
["When you are bored, you...","Start a new challenge","Call a friend or go out","Relax and watch something comfortable","Learn or build something"],
["Your walking style is...","Fast, always going somewhere","Medium, stopping to talk to people","Slow and relaxed","Steady, with a plan"],
["A friend asks for feedback on their work. You...","Say what is wrong, directly","Say good things first, with a smile","Say it gently, you don't want to hurt","Give detailed, honest notes"],
["If you had one superpower, it would be...","Super strength","Making everyone happy","Healing","Reading minds"],
["Stuck in traffic, you...","Get impatient and honk","Sing along to music","Stay calm and wait","Check the map for a faster way"],
["You win ₹10,000. You...","Invest in your big goal","Treat friends to a party","Save it for family","Compare options, then buy something useful"],
["In a meeting, you...","Lead and decide","Share ideas with energy","Listen and support","Ask detailed questions"],
["You like people who are...","Strong and honest","Fun and open","Kind and loyal","Smart and reliable"],
["The way you dress is...","Sharp and confident","Bright and trendy","Comfortable and simple","Neat and practical"],
["When plans change suddenly, you...","Adjust fast and take control","Enjoy the surprise","Feel uneasy and want time","Need to re-plan carefully"],
["You and a friend disagree. You...","Argue until you win","Try to joke it away","Give in to keep the peace","Present facts"],
["Your phone gallery has mostly...","Goals and useful screenshots","Selfies and group photos","Photos of family and special moments","Organised folders"],
["Your dream holiday is...","An adventure like trekking","A big party trip with friends","A quiet trip with family","A historic place, planned to the hour"],
["The thing you hate most is...","Losing","Being ignored","Fighting","Being wrong"],
["What do you do first in a new job?","Ask for big responsibilities","Meet everyone","Observe and help","Learn all the rules"],
["When you cook, you...","Cook fast and bold","Cook for a crowd and chat","Cook family favourites with love","Follow the recipe exactly"],
["Your favourite type of movie is...","Action","Comedy","Family drama","Mystery or thriller"],
["When you are angry, you...","Shout and say it","Talk about it with friends","Keep it inside","Go silent and think"],
["You are most proud of...","What you achieved","How many people like you","How people trust you","What you know"],
["A friend asks you to lead a project. You...","Say yes immediately","Say yes, if it's fun","Say maybe, if the team needs you","Say yes only if there's a clear plan"],
["During exams, you...","Study hard to be the top","Study in groups","Study steadily every day","Make notes and a schedule"],
["Your best quality at work is...","Drive","Enthusiasm","Patience","Accuracy"],
["Others find you...","Intense","Chatty","Gentle","Serious"],
["When you shop online, you...","Buy quickly, the best one","Buy what is trending","Buy trusted brands","Compare for hours"],
["A new rule is made in your group. You...","Question it if it slows us","Ask if it will be fun","Accept it for peace","Read every detail"],
["Your favourite part of a festival is...","The competition or games","The crowd and fun","The family time and food","The traditions and their meaning"],
["You get lost in a new city. You...","Choose a direction and go","Ask people and make friends","Stay calm and wait for help","Open the map and plan"],
["Your friends would call you...","Boss","Joker","Rock","Brain"],
["At the end of a day, you feel good when...","You got a lot done","You had fun with people","Everyone is okay and happy","Everything went as planned"],
["When a teammate makes a mistake, you...","Tell them directly","Cheer them up","Forgive and help","Explain how to avoid it"],
["You have a free hour. You...","Exercise or work on goals","Message friends","Rest with tea","Read or learn"],
["Your ideal boss is...","Strong and clear","Friendly and inspiring","Supportive and fair","Smart and organised"],
["Your biggest fear is...","Failure","Being forgotten","Losing loved ones","Making a big mistake"],
["When you tell a story, you...","Get straight to the point","Add drama and jokes","Tell it slowly with feeling","Include all the details"],
["When you meet new people, you seem...","Confident","Funny","Safe and friendly","Thoughtful"],
["Your study desk is...","Full of goals and targets","Full of stuff and stickers","Homely and calm","Perfectly tidy"],
["In a game, you...","Play to win at any cost","Play for fun","Play to help the team","Plan the strategy"],
["Your friend gets a promotion. You...","Feel motivated to do more","Throw a party","Feel truly happy for them","Wonder what skills they used"],
["Someone tells you to be patient. You...","Hate it","Try, but get distracted","Do it easily","Do it, with a plan"],
["Your inner voice says...","Go, go, go!","Let's enjoy!","It will be okay.","Think first."],
["A surprise guest arrives. You...","Take control and host","Welcome them with big joy","Make them comfortable with tea","Feel unprepared and worry"],
["In your friend group, you are the...","Leader","Entertainer","Peacemaker","Planner"],
["When you wake up, you...","Jump up and start","Check your phone for messages","Lie in bed a little longer","Follow your morning routine"],
["You are given a hard problem. You...","Attack it head on","Brainstorm with others","Take it slowly","Break it into parts"],
["You prefer a message that is...","Short and clear","Fun, with emojis","Warm and caring","Detailed and exact"],
["You choose a hobby for...","Competing","Meeting people","Relaxing","Mastering a skill"],
["How do you handle money?","Spend on big goals","Spend on fun","Save for safety","Track every rupee"],
["A rule seems unfair. You...","Fight it","Talk about it loudly","Wait and see","Study why it exists"],
["If you start a business, you want to...","Grow fast and be number one","Build a famous brand","Treat customers like family","Make the best quality product"],
["At a party, you...","Take over the game","Are the centre of attention","Help in the kitchen","Talk deeply with one or two people"],
["Your friends say you are bad at...","Listening","Staying focused","Saying no","Being spontaneous"],
["When you are praised, you...","Say thanks and move on","Light up and smile","Feel shy","Wonder if it's accurate"],
["You learn best when the teacher is...","Direct and strict","Funny and lively","Kind and patient","Clear and well prepared"],
["When something breaks, you...","Fix it right away","Call a friend to help","Stay calm and wait","Find the cause first"],
["You are best at...","Deciding","Motivating","Supporting","Analysing"],
["About rules, you think...","Rules can bend for results","Rules are boring","Rules keep us together","Rules should be followed"],
["In a crisis, you...","Take charge","Keep everyone's spirits up","Keep everyone calm","Figure out the facts"],
["The perfect gift for you is...","Something useful for my goal","A surprise party","A handwritten letter","A good book or gadget"],
["Your biggest weakness is...","Impatience","Distraction","Avoiding conflict","Overthinking"],
["If you could pick one word, it would be...","Win","Fun","Peace","Truth"],
["Someone cuts the queue. You...","Say something loudly","Make a joke about it","Ignore it","Note it and stay quiet"],
["In a team project, your role is...","Leader","Presenter","Helper","Researcher"],
["When you hear music, you...","Pump up the volume","Dance","Relax","Notice the lyrics"],
["Your plan for 5 years from now is...","Big goals, clear targets","Many people and adventures","A stable, happy life","A strong career in my field"],
["Your decision style is...","Quick","Emotional","Slow","Analytical"],
["You get a bad mark. You...","Get angry and work harder","Forget it and move on","Feel sad but accept it","Study what went wrong"],
["A friend cancels plans. You...","Say you'll do it alone","Find another plan with other friends","Say it's fine","Wonder what happened"],
["What do you love in a day?","Progress","Laughter","Peace","Order"],
["A group trip plan falls apart. You...","Take over the planning","Keep everyone laughing","Calm everyone down","Make a new clear plan"],
["You see someone struggling. You...","Give them a strong push","Cheer them up","Help right away","Think about what they really need"],
["Your main goal in a friendship is...","Respect","Fun","Trust","Honesty"],
["If you were a type of weather, you'd be...","A thunderstorm","A sunny day","A gentle breeze","A clear, cold night"],
["You prefer to work...","Alone, fast, and in charge","In a lively team","With a few trusted people","Alone, in quiet, with focus"],
["When you can't sleep, you...","Plan tomorrow's goals","Scroll and message friends","Listen to calm sounds","Think about problems"],
["Others admire you for...","Your confidence","Your energy","Your kindness","Your mind"],
["If a plan fails, you...","Try another way, fast","Laugh and try again","Accept it and stay calm","Study what failed"],
["A friend asks for a favour at a bad time. You...","Say no clearly","Say yes and try","Say yes, always","Check if you can really manage"],
["You are best described as...","Driven","Lively","Gentle","Thoughtful"],
["At the end of life, you want to be remembered as...","A winner and a leader","A joy to everyone","A caring person","A wise person"]
];
